services:
  - type: web
    name: opentrust-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://opentrust-backend.onrender.com 